name: "release-notes"

on:
  push:
    tags:
      - "*"

jobs:
  release-notes:
    name: "Regex Filtered Release Notes"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marcantondahmen/release-notes-action@master"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          filter: "^(feat|fix)"
          strict: true
